# Generated by Django 4.1 on 2024-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="photo",
            field=models.ImageField(default=2, upload_to="images"),
            preserve_default=False,
        ),
    ]
