# Generated by Django 4.1 on 2024-05-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0002_project_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="due_date",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
