# Generated by Django 4.1 on 2024-05-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0003_rename_due_date_task_date_alter_comment_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="www.project"
            ),
        ),
    ]
