# Generated by Django 4.1 on 2024-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0005_done_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="done",
            name="clicks",
        ),
        migrations.AddField(
            model_name="done",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
