# Generated by Django 4.1 on 2024-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0006_remove_done_clicks_done_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="done",
            name="value",
            field=models.BooleanField(default=False),
        ),
    ]
