# Generated by Django 4.1 on 2024-05-24 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0007_alter_done_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="done",
            old_name="value",
            new_name="done",
        ),
    ]
