# Generated by Django 4.1 on 2024-05-24 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0008_rename_value_done_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="done",
            name="done",
        ),
    ]
