# Generated by Django 4.1 on 2024-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0009_remove_done_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="done",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
